make:
	g++ -lpthread -lz  -DTIMING -Ofast -ffast-math  -I/home/kyss/htslib-1.12/ -L/home/kyss/htslib-1.12 -lhts BamBlock.h block_mul.cpp Buffer.cpp Buffer.h BamBlock.cpp -o main
clean:
	rm -rf ./main
